<script lang="ts">
// This file is auto-generated by keycloakify. Do not edit it manually.
// Hash: bb2ed1fb7504c6a04d36fcf2353a43a4c07847b8dc524a78b19ef7a9b3520c55

  import type { Component } from 'svelte';
  import type { KcContext } from './kc.gen';

  const { kcContext, Fallback }: { kcContext: KcContext; Fallback?: Component } = $props();

  const KcLoginPage = import("./login/KcPage.svelte");
</script>

{#if kcContext.themeType === 'login'}
  {#await KcLoginPage}
    {#if Fallback}
      <Fallback></Fallback>
    {/if}
  {:then { default: KcPage }}
    <KcPage {kcContext} />
  {/await}
{:else if kcContext.themeType === 'account'}
  <!-- account not implemented -->
{/if}