// This file is auto-generated by keycloakify. Do not edit it manually.
// Hash: 9aa1d1843f1db442cc1d576d9e84327769545b0957588aa5f9294e185ae56e92


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

export type ThemeName = "keycloakify-starter-svelte";

export const themeNames: ThemeName[] = ["keycloakify-starter-svelte"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}
